stages:
  - publish

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

publish:
  stage: publish
  image: python:3.14
  only:
    - master
  before_script:
    - apt-get update && apt-get install -y wget curl
    - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    - python3 get-pip.py
    - python3 -m pip install --upgrade pip
    - python3 -m pip install build twine
  script:
    - python3 -m build
    - python3 -m twine upload dist/* -u __token__ -p "$PYPI_API_TOKEN"
    - rm -rf dist build *.egg-info
  environment:
    name: production